global:
  scrape_interval: 15s

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

  # Enable public access
  web:
    external_url: 'https://studious-trout-j97xvpwj66c5w7x-9090.app.github.dev/'
    listen_address: ':9090'